export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOG_USER = 'LOG_USER';
export const LOGOUT = 'LOGOUT';
export const DELETE_USER = 'DELETE_USER';
export const EDIT_USER = 'EDIT_USER';
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';
export const RESET_SUCCESS = 'RESET_SUCCESS';

export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const SET_COURSE_LOADING = 'SET_AUTH_LOADING';
export const SET_COURSE_ERROR = 'SET_COURSE_ERROR';
export const RESET_COURSE_SUCCESS = 'RESET_COURSE_SUCCESS';
